openapi: 3.1.0
info:
  title: API for Spelldle.com
  version: "0.6"
servers:
  - url: /api
    description: base API url
paths:
  /register:
    post:
      security:
        - BasicAuth: []
      summary: attempt registration
      description:
        api recieves registration information and attemps to register new
        user
      responses:
        "201":
          description: successfully created
          content:
            application/json:
              schema: {}
        "401":
          description: username already exists
        "404":
          description: not found
        "500":
          description: server error
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
