openapi: 3.1.0
info:
  title: API for Spelldle.com
  version: "0.6"
servers:
  - url: /api
    description: base API url
paths:
  /register:
    post:
      security:
        - BasicAuth: []
      summary: attempt registration
      description:
        api recieves registration information and attemps to register new
        user
      responses:
        "201":
          description: successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response_register_login"
        "401":
          description: username already exists
        "404":
          description: not found
        "500":
          description: server error
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    user_data_personal:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
    user_data_account:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    auth_data_all_tokens:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
    user_id:
      type: number
      minimum: 0
    valid:
      type: boolean
    response_register_login:
      type: object
      properties:
        user_data_personal:
          $ref: "#/components/schemas/user_data_personal"
        user_data_tokens:
          $ref: "#/components/schemas/auth_data_all_tokens"
        user_data_account:
          $ref: "#/components/schemas/user_data_account"
        user_id:
          $ref: "#/components/schemas/user_id"
        valid:
          $ref: "#/components/schemas/valid"
